# Service Account for AWS Load Balancer Controller
# The role ARN annotation is added during deployment via CI/CD
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: ${LB_CONTROLLER_ROLE_ARN}
